#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

PATH=/usr/local/bin:$PATH

payload=$TMPDIR/phabricator-resource-request

cat > $payload <&0


conduit_uri=$(jq -r '.source.uri // ""' < $payload)
diff=$(jq -r '.version.diff // ""' < $payload)
conduit_token=$(jq -r '.source.token // ""' < $payload)

$(dirname $0)/commands/check.py $1 >&3 < $payload
